### ISSUE TITLE
Why not use the 'X-Github-Event' header?

### ISSUE THREAD

**Issue by Siilwyn** [doowb/typeof-github-event#1]
Wondering what this module offers that can't be retrieved from the `X-Github-Event` header. :thinking:

**Comment by doowb** [comment]
I built this for systems that don't have access to the headers. At the time I had a GitHub webhook posting directly into firebase and was using `firebase-queue` to process the events. Since then I use FaaS (Functions as a Service) where I can see the headers before processing the payload.

**Comment by Siilwyn** [comment]
Thanks for the informative reply!
